title:              Kombucha Summit Blog
email:              info@kombuchasummit.com
description:        Stories from the world of Kombucha.
author:             Good Culture Kombucha Ltd.
# baseurl:            "/KombuchaBlog"
# url:                "https://supertrupert.github.io/KombuchaBlog"

# Social Profiles
twitter_username:
github_username:
facebook_username:  Kombuchasummit
linkedin_username:  kombucha-summit
instagram_username: kombuchasummit

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-142385974-2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           100
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

permalink: none
